### ISSUE TITLE
Slider Component Doesn't work with navigation

### ISSUE THREAD

**Issue by arindam-p** [TahaSh/veloxi#1]
Hello Team,

I started using Veloxi for my product where the horizontal curved slider is wrapped in a react component.  It works the first time but doesn't work next time after donig some navigation.

Looks like there is no good way to unmount Veloxi once initialized. Can you please help out here?

**Comment by arindam-p** [comment]
I need a `app.destroy()` method which does all the cleanup so that I can instantiate this again if needed.

**Comment by arindam89** [comment]
Any updates?

**Comment by TahaSh** [comment]
@geekpaul-safe @arindam89 Thank you for letting me know about this. I'm currently working on a major update for Veloxi, and I will get to this very soon. I will update you as soon as possible. 😄

**Comment by arindam89** [comment]
Thank you @TahaSh looking forward to it. What I am looking for primarily is to be able to manage the lifecycle of the app which I can hook with react component lifecycle and it should work.

**Comment by arindam89** [comment]
Any ETA for the major update @TahaSh  :)

**Comment by TahaSh** [comment]
@arindam89 very soon! It should be a couple of days, I think.

**Comment by TahaSh** [comment]
@arindam89 @geekpaul-safe Veloxi 0.4.0 is out. You can now destroy a specific plugin or all plugins using `app.destroy`.

- To destroy a specific plugin: `app.destroy('PluginName')`.
- To destroy all plugins: `app.destroy()`.

To re-instantiate the plugins, you need to call `app.addPlugin(PluginConstructor)`. And don't forget to re-add all plugin event listeners, like `app.onPluginEvent(Plugin, EventName, () => {})`.

Or if you just want to reset the plugin, after navigation for example, which is what @geekpaul-safe described above, you can call `app.reset('PluginName')`. Using `app.reset`, you don't need to re-add plugin event listeners, they will be added automatically for you.

Please let me know if you have any questions. Any feedback is appreciated 🙏

**Comment by arindam89** [comment]
Superb. Thank you so much @TahaSh

**Comment by arindam89** [comment]
@TahaSh It worked great with the lifecycle, I can mount and unmount easily.

Next hurdle for me is performance. I know Veloxi is perf focused, so I used the horizontal slider demo for a date slider. It works great with the number of elements which are Veloxi views are limited like say one month worth of data.

But when the same is extended for 6months dates which is almost 180 veloxi views performance is taking a hit. I am sharing a video for the same here attached.

So, question I have is if I am to implement this in some Virtualized list or something, is there a easy way to keep get performance intact even for a large data set.

https://drive.google.com/file/d/1UpIAWn2wrMqdEf4CUBuEJM3FY0bhkqJ3/view?usp=share_link

**Comment by TahaSh** [comment]
@arindam89 Thank you for reporting this. After debugging, I found that the issue is partly due to how views are rendered in Veloxi and partly due to the way the plugin itself works. I'll update you as soon as I push the fixes.

**Comment by TahaSh** [comment]
@arindam89 I've released a new version (v0.5.0) with rendering fixes. Please update to it and use this improved version of the CurveNavPlugin: https://gist.github.com/TahaSh/2483798ee67a097ac5a127db17f026b0

I've tested it with 500 views, and it maintained 60fps most of the time. Can you please test it and let me know if you still see any issues? Thanks!

**Comment by arindam89** [comment]
This worked like a charm, super work! thanks for supporting us here @TahaSh

**Comment by TahaSh** [comment]
@arindam89 I'm really glad to hear that! Thank you!
